package cz.fi.muni.pa165.soccermanager.api.exceptions;

public enum ErrorStatus {
    RESOURCE_NOT_FOUND, 
    TEAM_ALREADY_ASSIGNED, 
    NO_MORE_ADMINISTRATOR, 
    RESOURCE_ALREADY_EXISTS, 
    PLAYER_IS_IN_TEAM, 
    NO_PLAYER_IN_TEAM, 
    TOO_MANY_PLAYERS_IN_TEAM,
    MATCH_DATE_IN_THE_FUTURE,
    MATCH_ALREADY_SIMULATED,
    MATCH_NOT_SIMULATED
}
